vim.cmd([[colorscheme vscode]])
-- vim.cmd([[colorscheme tokyonight]])
-- vim.cmd([[colorscheme solarized-osaka]])
-- local c = require("vscode.colors").get_colors()
-- require("vscode").setup({
-- 	-- Enable transparent background
-- 	transparent = true,
-- 	--
-- 	-- -- Enable italic comment
-- 	italic_comments = true,
-- 	--
-- 	-- -- Disable nvim-tree background color
-- 	disable_nvimtree_bg = false,
-- 	--
-- 	-- -- Override colors (see ./lua/vscode/colors.lua)
-- 	-- color_overrides = {
-- 	-- 	vscLineNumber = "#FFFFFF",
-- 	-- },
-- 	--
-- 	-- -- Override highlight groups (see ./lua/vscode/theme.lua)
-- 	group_overrides = {
-- 		-- this supports the same val table as vim.api.nvim_set_hl
-- 		-- use colors from this colorscheme by requiring vscode.colors!
-- 		Cursor = { fg = "#ff6161", bg = "green", bold = true },
-- 	},
-- })
